# Generated by Django 4.0.2 on 2022-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn42auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dn42user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
