# Generated by Django 4.0.2 on 2022-02-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn42auth', '0002_alter_dn42user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn42user',
            name='username',
        ),
        migrations.AddField(
            model_name='dn42user',
            name='dn42_mntner',
            field=models.CharField(default='INVALID-MNT', max_length=200, unique=True, verbose_name='DN42 maintainer object'),
            preserve_default=False,
        ),
    ]
