# Generated by Django 4.0.2 on 2022-02-04 04:05

from django.db import migrations
import dn42auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('dn42auth', '0003_remove_dn42user_username_dn42user_dn42_mntner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dn42user',
            managers=[
                ('objects', dn42auth.models.UserManager()),
            ],
        ),
    ]
