# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('asn', models.IntegerField(verbose_name='AS Number')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint external IP/hostname')),
                ('wg_privkey', models.CharField(max_length=150, verbose_name='Wireguard private key')),
                ('wg_pubkey', models.CharField(max_length=150, verbose_name='Wireguard public key')),
                ('wg_peer_pubkey', models.CharField(max_length=150, verbose_name='Wireguard peer public key')),
                ('wg_port', models.IntegerField(verbose_name='Wireguard port')),
            ],
            options={
                'verbose_name': 'Peering',
                'verbose_name_plural': 'Peerings',
            },
        ),
    ]
