# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peeringmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peering',
            name='name',
        ),
        migrations.AddField(
            model_name='peering',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
