# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0003_peering_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='peering',
            name='bandwidth_community',
            field=models.IntegerField(choices=[(21, '≥0.1mbit'), (22, '≥1mbit'), (23, '≥10mbit'), (24, '≥100mbit'), (25, '≥1gbit')], default=21, help_text='Used to set BGP communities', verbose_name='Link bandwidth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peering',
            name='endpoint_internal',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Endpoint internal IP'),
            preserve_default=False,
        ),
    ]
