# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0004_auto_20171101_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='peering',
            name='vpn_type',
            field=models.CharField(choices=[('wireguard', 'Wireguard')], default='wireguard', max_length=50, verbose_name='VPN type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peering',
            name='asn',
            field=models.IntegerField(help_text='Your MNTNER object must be listed as mnt-by for the AS', verbose_name='AS Number'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='bandwidth_community',
            field=models.IntegerField(choices=[(21, '≥0.1mbit'), (22, '≥1mbit'), (23, '≥10mbit'), (24, '≥100mbit'), (25, '≥1gbit')], default=24, help_text="Used to set <a href='https://wiki.dn42/howto/Bird-communities'>BGP communities</a>", verbose_name='Link bandwidth'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='endpoint',
            field=models.CharField(help_text='Hostname/IP and port, e.g. example.org:1234, 127.0.0.1:1234, [::1]:1234', max_length=200, verbose_name='Wireguard endpoint'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='endpoint_internal',
            field=models.GenericIPAddressField(help_text='The routers IP within dn42. This will be used for the BGP session', verbose_name='Internal router IP'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='router',
            field=models.CharField(choices=[('at-grz.gw.lutoma.dn42', 'Graz, Austria'), ('de-scn.gw.lutoma.dn42', 'Saarbrücken, Germany'), ('ca-mon.gw.lutoma.dn42', 'Montréal, Canada'), ('us-lax.gw.lutoma.dn42', 'Los Angeles, USA')], max_length=50, verbose_name='Router'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='wg_peer_pubkey',
            field=models.CharField(help_text="See <a href='https://www.wireguard.com/quickstart/#key-generation'>Wireguard manual</a> on how to generate the keys", max_length=150, verbose_name='Wireguard public key'),
        ),
        migrations.AlterUniqueTogether(
            name='peering',
            unique_together=set([('asn', 'router'), ('router', 'wg_port')]),
        ),
    ]
