# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0005_auto_20171101_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peering',
            name='endpoint_internal',
            field=models.GenericIPAddressField(help_text='The routers IP within dn42. This will be used for the BGP session', protocol='IPv4', verbose_name='Internal router IP'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='vpn_type',
            field=models.CharField(choices=[('wireguard', 'Wireguard')], default='wireguard', help_text='Peering is also possible using OpenVPN/GRE/…, but only with manual setup for now.', max_length=50, verbose_name='VPN type'),
        ),
    ]
