# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0006_auto_20171101_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('host_external', models.CharField(max_length=100, verbose_name='External host')),
                ('host_internal', models.CharField(max_length=100, verbose_name='Internal host')),
                ('ip_internal', models.CharField(max_length=100, verbose_name='Internal IP')),
                ('wg_last_port', models.IntegerField(default=42400, verbose_name='Last allocated wireguard port')),
            ],
        ),
        migrations.AlterField(
            model_name='peering',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peeringmanager.Router', verbose_name='Router'),
        ),
        migrations.AlterUniqueTogether(
            name='peering',
            unique_together=set([('router', 'wg_port'), ('asn', 'router'), ('endpoint_internal', 'router')]),
        ),
    ]
