# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0008_auto_20171103_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='peering',
            name='name',
            field=models.CharField(default='foo', help_text='Used for the interface name (wg.name) and bird peering name etc.', max_length=25, verbose_name='Peering name'),
            preserve_default=False,
        ),
    ]
