# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0009_peering_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='active',
            field=models.BooleanField(default=True, help_text='Users can only create peerings to active routers', verbose_name='Active'),
        ),
    ]
