# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0010_router_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ['location']},
        ),
        migrations.AddField(
            model_name='router',
            name='lg_id',
            field=models.IntegerField(default=0, verbose_name='Looking Glass ID'),
        ),
    ]
