# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0011_auto_20171104_0647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peering',
            unique_together=set([('router', 'name'), ('router', 'asn'), ('router', 'endpoint_internal'), ('router', 'wg_port')]),
        ),
    ]
