# Generated by Django 4.0.2 on 2022-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0015_alter_peering_name_alter_router_lg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='flag_emoji',
            field=models.CharField(default='🇪🇺', max_length=10, verbose_name='Location flag emoji'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='bandwidth_community',
            field=models.IntegerField(choices=[(21, '≥0.1mbit'), (22, '≥1mbit'), (23, '≥10mbit'), (24, '≥100mbit'), (25, '≥1gbit')], default=24, help_text='Used to set <a href="https://dn42.eu/howto/Bird-communities">BGP communities</a>', verbose_name='Link bandwidth'),
        ),
    ]
