# Generated by Django 4.0.2 on 2022-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0018_alter_peering_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peering',
            name='mntner',
            field=models.CharField(max_length=200, verbose_name='Maintainer object'),
        ),
    ]
