# Generated by Django 4.0.2 on 2022-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0019_alter_peering_mntner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peering',
            name='name',
            field=models.CharField(help_text='A human-readable name for this peering. Usually your nickname or a network name. Used for the Wireguard interface name, in the looking glass, and similar places. Lowercase ASCII only, max. 12 chars.', max_length=12, verbose_name='Peering name'),
        ),
    ]
