# Generated by Django 4.0.2 on 2022-03-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0020_alter_peering_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peering',
            name='endpoint_internal_v4',
            field=models.GenericIPAddressField(blank=True, help_text='Internal DN42 address of your router', null=True, protocol='IPv4', verbose_name='Internal IPv4 address'),
        ),
        migrations.AlterField(
            model_name='peering',
            name='endpoint_internal_v6',
            field=models.GenericIPAddressField(blank=True, help_text='Link-local IPv6 address of your router', null=True, protocol='IPv6', verbose_name='Link-local IPv6 address'),
        ),
    ]
