# Generated by Django 4.0.2 on 2022-07-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0021_alter_peering_endpoint_internal_v4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peering',
            name='router_endpoint_internal_v6',
            field=models.GenericIPAddressField(blank=True, default='fe80::acab', help_text='Link-local IPv6 address of my router', null=True, protocol='IPv6', verbose_name='Link-local IPv6 address router'),
        ),
    ]
