# Generated by Django 4.1.2 on 2023-12-29 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peeringmanager', '0022_peering_router_endpoint_internal_v6'),
    ]

    operations = [
        migrations.AddField(
            model_name='peering',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='peering',
            name='last_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last seen up'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peering',
            name='name',
            field=models.CharField(help_text='A human-readable name for this peering. Usually your nickname or a network name. Used for the Wireguard interface name, in the looking glass, and similar places. Lowercase ASCII only, max. 12 chars, needs to start with a non-number. <br><br><strong>The point of this name is to make it easier to identify peerings in command outputs for _me_ , so please don\'t use generic names like "home", "router" or "lutomanyc".</strong>', max_length=12, verbose_name='Peering name'),
        ),
    ]
